modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png"
# A text field displayed in the mod UI
credits="Guns by TaCZ Team, Skins by Default642172" #optional
# A text field displayed in the mod UI

authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tacz"
    mandatory=true
    versionRange="[1.1.4,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=false
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=false
    versionRange="[5.9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=false
versionRange="[11,)"
ordering="NONE"
side="BOTH"

